// Serves the app that the KaibanJS crew generated (generated/index.html).
import 'dotenv/config';
import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { activeProvider } from './llm.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const generatedDir = path.join(__dirname, '..', 'generated');
const app = express();

app.use(express.static(generatedDir));

// Friendly nudge if the crew hasn't built the app yet.
app.get('/', (_req, res, next) => {
  if (fs.existsSync(path.join(generatedDir, 'index.html'))) return next();
  res
    .status(200)
    .type('html')
    .send(
      `<body style="font-family:system-ui;max-width:640px;margin:80px auto;padding:0 20px;line-height:1.6">
        <h1>Nothing built yet</h1>
        <p>The KaibanJS crew hasn't generated the app. Run:</p>
        <pre style="background:#f4f4f5;padding:16px;border-radius:8px">npm run build:app</pre>
        <p>Then reload this page. Backend: <b>${activeProvider()}</b></p>
      </body>`
    );
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n  Serving the AI-built to-do app at http://localhost:${PORT}`);
  console.log(`  (generated by the KaibanJS crew · backend: ${activeProvider()})\n`);
});
